DISTRO_PACKAGES = {
    "arch": [
        "python",
        "base-devel",
        "cmake",
        "ninja",
        "git",
        "qt6-base",
        "qt6-tools",
        "qt6-declarative",
        "qt6-svg",
    ],
    "debian": [
        "python3",
        "python3-venv",
        "build-essential",
        "cmake",
        "ninja-build",
        "git",
        "qt6-base-dev",
        "qt6-tools-dev",
        "qt6-declarative-dev",
        "libqt6svg6-dev",
    ],
    "fedora": [
        "python3",
        "python3-devel",
        "cmake",
        "ninja-build",
        "git",
        "gcc",
        "gcc-c++",
        "make",
        "qt6-qtbase-devel",
        "qt6-qttools-devel",
        "qt6-qtdeclarative-devel",
        "qt6-qtsvg-devel",
    ],
}